// This file is auto-generated by build.js during the Vercel build step
// (using Vercel's built-in VERCEL_ENV variable). This checked-in copy is
// just a safe fallback for local/direct file preview before any build runs.
window.IS_DEV_ENV = true;
window.VERCEL_ENV = 'development';
