// This file is auto-generated by build.js during the Vercel build step
// (using the ENVIRONMENT and TWM_BASE_URL project env vars). This checked-in
// copy is just a safe fallback for local/direct file preview before any
// build runs, and defaults to production.
window.ENVIRONMENT = 'prod';
window.TWM_BASE_URL = 'https://travelwithme-zf9f.onrender.com';
